project:
  type: website

website:
  title: "AY2023/24S1 Team 10"
  navbar:
    background: primary
    search: True
    right:
      - href: index.qmd
        text: "Overview"
      - href: about.qmd
        text: "About"
      - href: methodology.qmd
        text: "Methodology"
      - href: results.qmd
        text: "Results and Discussion"
      - href: media/SMT201_Team10_Project_Poster.jpg
        text: "Poster"
      - text: "Webmaps"
        menu: 
          - text: "Before Flood True Colour Composite"
            href: Before_Flood_3D/GeoEye-TCC-Before/index.html
          - text: "Before Flood False Colour Composite"
            href: Before_Flood_3D/GeoEye-FCC-Before/index.html
          - text: "Before Flood Green Normalized Difference Vegetation Index (GNDVI)"
            href: Before_Flood_3D/GeoEye-GNDVI-Before/index.html
          - text: "Before Flood Renormalized Difference Vegetation Index (RDVI)"
            href: Before_Flood_3D/GeoEye-RDVI-Before/index.html
          - text: "After Flood True Colour Composite"
            href: After_Flood_3D/GeoEye-TCC-After/index.html
          - text: "After Flood False Colour Composite"
            href: After_Flood_3D/GeoEye-FCC-After/index.html
          - text: "After Flood Green Normalized Difference Vegetation Index (GNDVI)"
            href: After_Flood_3D/GeoEye-GNDVI-After/index.html
          - text: "After Flood Renormalized Difference Vegetation Index (RDVI)"
            href: After_Flood_3D/GeoEye-RDVI-After/index.html

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4

editor: visual

