project:
  type: website

website:
  title: "AY2023/24S1 Team 10"
  navbar:
    background: dark
    search: True
    left:
      - href: index.qmd
        text: Overview
      - href: about.qmd
        text: About
      - href: report.qmd
        text: Report

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

