project:
  type: website

website:
  title: "AY2023/24S1 Team 10"
  navbar:
    background: primary
    search: True
    right:
      - href: index.qmd
        text: Overview
      - href: about.qmd
        text: About
      - href: report.qmd
        text: Report
      - href: results.qmd
        text: Results and Discussion
      - text: "Webmaps"
        menu: 
          - text: "Before Flood True Colour Composite"
            href: Before_Flood_3D/GeoEye-TCC-Before/index.html
          - text: "Before Flood False Colour Composite"
            href: Before_Flood_3D/GeoEye-FCC-Before/index.html
          - text: "Before Flood GNDVI"
            href: Before_Flood_3D/GeoEye-GNDVI-Before/index.html
          - text: "Before Flood RDVI"
            href: Before_Flood_3D/GeoEye-RDVI-Before/index.html

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

