project:
  type: website

website:
  title: "AY2023/24S1 Team 10"
  navbar:
    background: primary
    search: True
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Us"
      - href: overview.qmd
        text: "Overview"
      - href: methodology.qmd
        text: "Methodology"
      - href: results.qmd
        text: "Results and Discussion"
      - href: lessons.qmd
        text: "Lessons Learned"
      - href: poster.qmd
        text: "Poster"
      - text: "3D Webmap"
        href: 3D Model/index.html

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

editor: visual

