project:
  type: website

website:
  title: "AY2023/24S1 Team 10 - FloodScape:Unearthing Resilience"
  navbar:
    background: dark
    search: True
    left:
      - href: index.qmd
        text: Overview
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

