project:
  type: website

website:
  title: "AY2023/24S1 Team 10"
  navbar:
    background: primary
    search: True
    left:
      - href: index.qmd
        text: Overview
      - href: about.qmd
        text: About
      - href: report.qmd
        text: Report
      - href: results.qmd
        text: Results and Discussion
      - text: "Webmaps"
        menu: 
          - text: "Punggol Pre-school Distibution"
            href: qgis2web/index.html
          - text: "Derna 3D Model"
            href: qgis2threejs/index.html

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

